# Generated by Django 5.1.4 on 2024-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='numero_habitaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
