# Generated by Django 5.1.4 on 2024-12-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_remove_propiedad_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
