# Generated by Django 5.1.4 on 2024-12-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
